version: 2
updates:
  - package-ecosystem: gomod
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "11:01"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: "wednesday"
      time: "11:02"

  - package-ecosystem: docker
    directory: "/"
    schedule:
      interval: weekly
      day: "monday"
      time: "11:03"
