repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: trailing-whitespace # Trims trailing whitespace
      - id: end-of-file-fixer # Ensures files end in a newline
      - id: mixed-line-ending # Replaces mixed line endings with a consistent one
        args: [--fix=lf]
      - id: check-toml # Checks TOML files for syntax errors
      - id: check-yaml # Checks YAML files for syntax errors
      - id: check-json # Checks JSON files for syntax errors
      - id: check-merge-conflict # Checks for files that contain merge conflict strings
      - id: check-added-large-files # Prevents committing large files
        args: [--maxkb=500]

  - repo: https://github.com/golangci/golangci-lint
    rev: v2.11.4
    hooks:
      - id: golangci-lint
